[project]
name = "historymcp"
version = "0.1.0"
description = "MCP tool to fetch browser history"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.10.1",
    "pandas>=2.3.0",
    "requests>=2.32.4",
]
